fragment PostParts on Post {
  __typename
  title
  body
}

fragment HomepageParts on Homepage {
  __typename
  hero {
    __typename
    title
    description
    cta {
      __typename
      text
      href
    }
    image {
      __typename
      mobile
      desktop
      alt
    }
  }
  imageGroup {
    __typename
    left {
      __typename
      src
      alt
    }
    right {
      __typename
      src
      alt
    }
  }
  heroCards {
    __typename
    image
    title
  }
  stats {
    __typename
    number
    desc
  }
  servicesBlock {
    __typename
    topper
    title
    text
    button {
      __typename
      text
      href
    }
    cards {
      __typename
      title
      text
      href
      image {
        __typename
        mobile
        desktop
        alt
      }
    }
  }
  steps {
    __typename
    number
    title
    text
  }
  gallery {
    __typename
    caption
    image
  }
  quote {
    __typename
    text
    name
    background
  }
  ctaContact {
    __typename
    topper
    title
    phoneLabel
    emailLabel
    addressLabel
  }
  seo {
    __typename
    title
    description
    permalink
    eleventyNavigationKey
    eleventyNavigationOrder
    keywords
    image
  }
}

fragment ServicesParts on Services {
  __typename
  intro {
    __typename
    topper
    title
    text
  }
  serviceCards {
    __typename
    title
    description
    href
    image
  }
  seo {
    __typename
    title
    description
    image
  }
}

fragment ProjectsParts on Projects {
  __typename
  intro {
    __typename
    topper
    title
    text
  }
  gallery {
    __typename
    caption
    image
  }
  seo {
    __typename
    title
    description
    image
  }
}

fragment ContactParts on Contact {
  __typename
  contactBlock {
    __typename
    topper
    title
    text
  }
  details {
    __typename
    phoneLabel
    emailLabel
    addressLabel
  }
  seo {
    __typename
    title
    description
    image
  }
}
